In [43]:
# import necessary modules 
# please run this everytime you open it
import pandas as pd 
import numpy as np 
import matplotlib as plt 
import seaborn as sns
import re
import os

In [67]:
# run Validation notebook
%run Validation.ipynb

# Specialists

## Example of get_topic()

In [45]:
a = pd.read_csv("Specialists data/Covid_SourceRelevancev1-2020-10-04T1838-DataHunt.csv")
get_topic(a)

'Quote Source Relevance'

## Example to_reliability()

In [46]:
array = to_reliability("Specialists data", "Covid_SourceRelevancev1-2020-10-04T1838-DataHunt.csv", "T1.Q2")
array[0]

There are 0 rows where all values are missing
There are 0 cols where all values are missing


array([nan, nan, nan, 5, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, 2, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, 2, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, 5, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, 5, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, 5, nan, nan,
       1, 5, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan

In [47]:
# load the example data 
relevance = pd.read_csv("Specialists data/Covid_SourceRelevancev1-2020-10-04T1838-DataHunt.csv")
# select certain columns 
cols = ["quiz_task_uuid", "contributor_uuid", "question_label", "answer_label"]
relevance_q2 = relevance[relevance["question_label"] == "T1.Q2"]
relevance_q2 = relevance_q2.reindex(columns=cols)
relevance_q2.head()

quiz_task_uuid  \
1   9d4ac736-52b7-40df-b2a9-6164fa081960   
18  9d4ac736-52b7-40df-b2a9-6164fa081960   
40  9d4ac736-52b7-40df-b2a9-6164fa081960   
53  9d4ac736-52b7-40df-b2a9-6164fa081960   
73  9d4ac736-52b7-40df-b2a9-6164fa081960   

                        contributor_uuid question_label answer_label  
1   00f548b7-6b63-4b47-828e-8e416b6ca0e2          T1.Q2     T1.Q2.A1  
18  e44f5799-6915-45fd-874e-060f6afedcb9          T1.Q2     T1.Q2.A2  
40  fed45769-aa61-4b8b-847e-a9c799acce15          T1.Q2     T1.Q2.A2  
53  fb4ae4cc-234b-484a-b541-a8e3a9254a24          T1.Q2     T1.Q2.A1  
73  3bb03f58-5f09-4414-b54e-43a814b9b09a          T1.Q2     T1.Q2.A1

**Construct the reliability matrix, the left column is the contributor_uuid, each unit -> quiz_taskrun_uuid**

In [48]:
df = pd.pivot_table(relevance_q2, values='answer_label', index='contributor_uuid', columns='quiz_task_uuid', aggfunc=select)
# drop nan rows 
df = df.dropna(axis=1, how='all')
df.head(5)

quiz_task_uuid                       00ef0777-da36-47b0-94d4-135eb520bcfb  \
contributor_uuid                                                            
00f548b7-6b63-4b47-828e-8e416b6ca0e2                             T1.Q2.A5   
06e1eba7-c695-4495-85a7-2fb33ef9412c                                  NaN   
0b2ee377-65f2-4ac1-98da-5bc093fee7aa                             T1.Q2.A6   
0cdf31d0-1966-4f69-a0c8-c483788b5256                             T1.Q2.A2   
0e4b8a3e-2714-4b5f-ba10-bb576aaa5cc6                                  NaN   

quiz_task_uuid                       0214dcdb-838e-4947-8a8e-7cc8f8f2fce6  \
contributor_uuid                                                            
00f548b7-6b63-4b47-828e-8e416b6ca0e2                                  NaN   
06e1eba7-c695-4495-85a7-2fb33ef9412c                                  NaN   
0b2ee377-65f2-4ac1-98da-5bc093fee7aa                                  NaN   
0cdf31d0-1966-4f69-a0c8-c483788b5256                                  NaN   
0e4b8a3e-2714-4b5f-ba10-bb576aaa5cc6                                  NaN   

quiz_task_uuid                       08e6aae7-56c5-4c0f-8517-d2a7f2bc5895  \
contributor_uuid                                                            
00f548b7-6b63-4b47-828e-8e416b6ca0e2                                  NaN   
06e1eba7-c695-4495-85a7-2fb33ef9412c                                  NaN   
0b2ee377-65f2-4ac1-98da-5bc093fee7aa                                  NaN   
0cdf31d0-1966-4f69-a0c8-c483788b5256                                  NaN   
0e4b8a3e-2714-4b5f-ba10-bb576aaa5cc6                                  NaN   

quiz_task_uuid                       1b4d23d1-fa87-44fe-b5b2-1a5909246b66  \
contributor_uuid                                                            
00f548b7-6b63-4b47-828e-8e416b6ca0e2                                  NaN   
06e1eba7-c695-4495-85a7-2fb33ef9412c                                  NaN   
0b2ee377-65f2-4ac1-98da-5bc093fee7aa                                  NaN   
0cdf31d0-1966-4f69-a0c8-c483788b5256                                  NaN   
0e4b8a3e-2714-4b5f-ba10-bb576aaa5cc6                                  NaN   

quiz_task_uuid                       23699e71-779c-4a97-81aa-e0bdc8c69432  \
contributor_uuid                                                            
00f548b7-6b63-4b47-828e-8e416b6ca0e2                                  NaN   
06e1eba7-c695-4495-85a7-2fb33ef9412c                                  NaN   
0b2ee377-65f2-4ac1-98da-5bc093fee7aa                                  NaN   
0cdf31d0-1966-4f69-a0c8-c483788b5256                                  NaN   
0e4b8a3e-2714-4b5f-ba10-bb576aaa5cc6                                  NaN   

quiz_task_uuid                       3032089b-c0e4-4f39-ac05-98e135113625  \
contributor_uuid                                                            
00f548b7-6b63-4b47-828e-8e416b6ca0e2                                  NaN   
06e1eba7-c695-4495-85a7-2fb33ef9412c                                  NaN   
0b2ee377-65f2-4ac1-98da-5bc093fee7aa                                  NaN   
0cdf31d0-1966-4f69-a0c8-c483788b5256                                  NaN   
0e4b8a3e-2714-4b5f-ba10-bb576aaa5cc6                                  NaN   

quiz_task_uuid                       4479a237-11ec-4a69-bab1-090b44fb62a9  \
contributor_uuid                                                            
00f548b7-6b63-4b47-828e-8e416b6ca0e2                             T1.Q2.A5   
06e1eba7-c695-4495-85a7-2fb33ef9412c                                  NaN   
0b2ee377-65f2-4ac1-98da-5bc093fee7aa                             T1.Q2.A6   
0cdf31d0-1966-4f69-a0c8-c483788b5256                             T1.Q2.A5   
0e4b8a3e-2714-4b5f-ba10-bb576aaa5cc6                                  NaN   

quiz_task_uuid                       65fc3c92-5aef-4fef-a3c4-56145a077a33  \
contributor_uuid                                                            
00f548b7-6b63-4b47-828e-8e416b6ca0e2                             T

In [49]:
array = df.to_numpy()
array[0]

array(['T1.Q2.A5', nan, nan, nan, nan, nan, 'T1.Q2.A5', 'T1.Q2.A1', nan,
       nan, 'T1.Q2.A2', 'T1.Q2.A5', 'T1.Q2.A2', nan, nan, 'T1.Q2.A1', nan,
       'T1.Q2.A5', 'T1.Q2.A5', nan, 'T1.Q2.A3', nan, nan, 'T1.Q2.A3', nan,
       nan], dtype=object)

In [50]:
# iterate through all values in array and convert string to int 
for i in range(array.shape[0]):
    for j in range(array.shape[1]):
        cur = array[i][j]
        # if the current value is a string
        if not pd.isnull(cur):
            array[i][j] = int(array[i][j][-1])

In [51]:
df = pd.DataFrame(array)
df.head()

0    1    2    3    4    5    6    7    8    9   ...   16   17   18   19  \
0    5  NaN  NaN  NaN  NaN  NaN    5    1  NaN  NaN  ...  NaN    5    5  NaN   
1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN   
2    6  NaN  NaN  NaN  NaN  NaN    6    5  NaN    5  ...  NaN  NaN    7  NaN   
3    2  NaN  NaN  NaN  NaN  NaN    5  NaN  NaN  NaN  ...  NaN    5  NaN  NaN   
4  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN   

    20   21   22   23   24   25  
0    3  NaN  NaN    3  NaN  NaN  
1  NaN  NaN  NaN  NaN  NaN  NaN  
2  NaN  NaN  NaN    5  NaN  NaN  
3  NaN  NaN  NaN  NaN  NaN  NaN  
4  NaN  NaN  NaN  NaN  NaN  NaN  

[5 rows x 26 columns]

In [52]:
print(round(alpha(reliability_data=df, level_of_measurement='nominal'), 10))

0.191812762


## Example of ordinal

Example file: Evidence <br>
Question: 11

In [4]:
evidence = pd.read_csv("Specialists data/Covid_Evidencev1-2020-10-04T1836-DataHunt.csv")

In [71]:
compute_alpha("Specialists data", "Covid_Evidencev1-2020-10-04T1836-DataHunt.csv", "T1.Q11", "ordinal", 5)

0.01752

## Example of checklist

Example file: Covid_Reasoningv1-2020-10-04T1803-DataHunt.csv <br>
Question: 1 (cl)

In [82]:
reasoning = pd.read_csv("Specialists data/Covid_Reasoningv1-2020-10-04T1803-DataHunt.csv")
reasoning = reasoning[reasoning["question_label"] == "T1.Q1"]
reasoning = reasoning.reindex(columns=cols)
# reasoning.to_excel("example1.xlsx")
example = pd.get_dummies(reasoning, columns = ["answer_label"])
# example.to_excel("example2.xlsx")

In [90]:
example_three = example.groupby(["quiz_task_uuid", "contributor_uuid"]).agg(sum)
example_three = example_three.reset_index()
# example_three.to_excel("example_three.xlsx")

In [93]:
example_four = pd.melt(example_three, id_vars=["quiz_task_uuid", "contributor_uuid"], 
                                  var_name = "choice", 
                                  value_name = "value")
example_four = example_four.sort_values(by=["quiz_task_uuid", "contributor_uuid", "choice"])
# example_four.to_excel("example_four.xlsx")

TypeError: can only concatenate list (not "str") to list

In [95]:
example_five = example_four.copy()
example_five["choice"] = example_five["quiz_task_uuid"].str.slice(start=0, stop=6) + " " + example_five["choice"]
example_five.head()

quiz_task_uuid  \
0    085cde3c-97c3-44a4-a773-37f7d5704107   
136  085cde3c-97c3-44a4-a773-37f7d5704107   
272  085cde3c-97c3-44a4-a773-37f7d5704107   
408  085cde3c-97c3-44a4-a773-37f7d5704107   
544  085cde3c-97c3-44a4-a773-37f7d5704107   

                         contributor_uuid                        choice  value  
0    00f548b7-6b63-4b47-828e-8e416b6ca0e2  085cde answer_label_T1.Q1.A1      0  
136  00f548b7-6b63-4b47-828e-8e416b6ca0e2  085cde answer_label_T1.Q1.A2      0  
272  00f548b7-6b63-4b47-828e-8e416b6ca0e2  085cde answer_label_T1.Q1.A3      1  
408  00f548b7-6b63-4b47-828e-8e416b6ca0e2  085cde answer_label_T1.Q1.A4      0  
544  00f548b7-6b63-4b47-828e-8e416b6ca0e2  085cde answer_label_T1.Q1.A5      0

In [97]:
example_six = pd.pivot_table(example_five, values='value', index='contributor_uuid', 
                          columns='choice', 
                          aggfunc=select)
example_six.to_excel("example_6.xlsx")

In [99]:
example_six.head()

choice                                085cde answer_label_T1.Q1.A1  \
contributor_uuid                                                     
00f548b7-6b63-4b47-828e-8e416b6ca0e2                           0.0   
1119f9ca-0dce-4a9e-b71e-5983833e8bbe                           NaN   
172e9a38-d3e4-453e-8556-18bbd0fcb07e                           NaN   
214e3374-4279-4748-80c8-ea8a76ad7cbc                           0.0   
343ecb7a-aeb5-4b21-9e9c-df545dafba99                           NaN   

choice                                085cde answer_label_T1.Q1.A2  \
contributor_uuid                                                     
00f548b7-6b63-4b47-828e-8e416b6ca0e2                           0.0   
1119f9ca-0dce-4a9e-b71e-5983833e8bbe                           NaN   
172e9a38-d3e4-453e-8556-18bbd0fcb07e                           NaN   
214e3374-4279-4748-80c8-ea8a76ad7cbc                           1.0   
343ecb7a-aeb5-4b21-9e9c-df545dafba99                           NaN   

choice                                085cde answer_label_T1.Q1.A3  \
contributor_uuid                                                     
00f548b7-6b63-4b47-828e-8e416b6ca0e2                           1.0   
1119f9ca-0dce-4a9e-b71e-5983833e8bbe                           NaN   
172e9a38-d3e4-453e-8556-18bbd0fcb07e                           NaN   
214e3374-4279-4748-80c8-ea8a76ad7cbc                           0.0   
343ecb7a-aeb5-4b21-9e9c-df545dafba99                           NaN   

choice                                085cde answer_label_T1.Q1.A4  \
contributor_uuid                                                     
00f548b7-6b63-4b47-828e-8e416b6ca0e2                           0.0   
1119f9ca-0dce-4a9e-b71e-5983833e8bbe                           NaN   
172e9a38-d3e4-453e-8556-18bbd0fcb07e                           NaN   
214e3374-4279-4748-80c8-ea8a76ad7cbc                           0.0   
343ecb7a-aeb5-4b21-9e9c-df545dafba99                           NaN   

choice                                085cde answer_label_T1.Q1.A5  \
contributor_uuid                                                     
00f548b7-6b63-4b47-828e-8e416b6ca0e2                           0.0   
1119f9ca-0dce-4a9e-b71e-5983833e8bbe                           NaN   
172e9a38-d3e4-453e-8556-18bbd0fcb07e                           NaN   
214e3374-4279-4748-80c8-ea8a76ad7cbc                           0.0   
343ecb7a-aeb5-4b21-9e9c-df545dafba99                           NaN   

choice                                085cde answer_label_T1.Q1.A6  \
contributor_uuid                                                     
00f548b7-6b63-4b47-828e-8e416b6ca0e2                           0.0   
1119f9ca-0dce-4a9e-b71e-5983833e8bbe                           NaN   
172e9a38-d3e4-453e-8556-18bbd0fcb07e                           NaN   
214e3374-4279-4748-80c8-ea8a76ad7cbc                           0.0   
343ecb7a-aeb5-4b21-9e9c-df545dafba99                           NaN   

choice                                15ef35 answer_label_T1.Q1.A1  \
contributor_uuid                                                     
00f548b7-6b63-4b47-828e-8e416b6ca0e2                           0.0   
1119f9ca-0dce-4a9e-b71e-5983833e8bbe                           NaN   
172e9a38-d3e4-453e-8556-18bbd0fcb07e                           0.0   
214e3374-4279-4748-80c8-ea8a76ad7cbc                           0.0   
343ecb7a-aeb5-4b21-9e9c-df545dafba99                           NaN   

choice                                15ef35 answer_label_T1.Q1.A2  \
contributor_uuid                                                     
00f548b7-6b63-4b47-828e-8e416b6ca0e2                           0.0   
1119f9ca-0dce-4a9e-b71e-5983833e8bbe                           NaN   
172e9a38-d3e4-453e-8556-18bbd0fcb07e                           0.0   
214e3374-4279-4748-80c8-ea8a76ad7cbc                           0.0   
343ecb7a-aeb5-4b21-9e9c-df545dafba99                           NaN   

choice                                15ef35 answer_label_T1.Q1.A3  \
co

In [101]:
array = example_six.to_numpy()

In [102]:
array

array([[ 0.,  0.,  1., ...,  0.,  0.,  0.],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]])

In [103]:
print(round(alpha(reliability_data=array, level_of_measurement='nominal'), 6))

0.265466


## compute_alpha()

In [142]:
compute_alpha("Specialists data", "Covid_SourceRelevancev1-2020-10-04T1838-DataHunt.csv", "T1.Q2", "nominal", 6)

There are 0 rows where all values are missing
There are 0 cols where all values are missing


0    1    2    3    4    5    6    7    8    9    ...  248  249  250  251  \
0  NaN  NaN  NaN    5  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN   
1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN   
2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN   
3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN   
4  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN   

   252  253  254  255  256  257  
0  NaN  NaN  NaN  NaN  NaN  NaN  
1  NaN  NaN  NaN  NaN  NaN  NaN  
2  NaN  NaN  NaN  NaN  NaN  NaN  
3  NaN  NaN  NaN  NaN  NaN  NaN  
4  NaN  NaN  NaN  NaN  NaN  NaN  

[5 rows x 258 columns]

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[0. 0. 0. 0. 0. 0. 0. 0.]
[[-0. -0. -0. -0. -0. -0. -0. -0.]
 [-0. -0. -0. -0. -0. -0. -0. -0.]
 [-0. -0. -0. -0. -0. -0. -0. -0.]
 [-0. -0. -0. -0. -0. -0. -0. -0.]
 [-0. -0. -0. -0. -0. -0. -0. -0.]
 [-0. -0. -0. -0. -0. -0. -0. -0.]
 [-0. -0. -0. -0. -0. -0. -0. -0.]
 [-0. -0. -0. -0. -0. -0. -0. -0.]]
[[0. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 1. 1. 1. 1.]
 [1. 1. 1. 0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 0.]]
[[-0. -0. -0. -0. -0. -0. -0. -0.]
 [-0. -0. -0. -0. -0. -0. -0. -0.]
 [-0. -0. -0. -0. -0. -0. -0. -0.]
 [-0. -0. -0. -0. -0. -0. -0. -0.]
 [-0. -0. -0. -0. -0. -0. -0. -0.]
 [-0. -0. -0. -0. -0. -0. -0. -0.]
 [-0. -0. -0. -0. -0. -0. -0. -0.]
 [-0. -0. -0. 

C:\Users\thefi\Desktop\PE-Validation-Fall-20\krippendorff.py:283: RuntimeWarning: invalid value encountered in double_scalars


nan

In [146]:
compute_alpha("Specialists data", "Covid_Evidencev1-2020-10-04T1836-DataHunt.csv", "T1.Q6", "nominal", 6)

There are 0 rows where all values are missing
There are 0 cols where all values are missing


0    1    2    3    4    5    6    7    8    9    10   11   12   13   14  \
0  NaN  NaN    3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN    3  NaN  NaN  NaN  NaN  NaN   
2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
3  NaN  NaN  NaN  NaN  NaN    2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
4  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   

    15   16   17  
0  NaN  NaN  NaN  
1  NaN  NaN  NaN  
2  NaN    2  NaN  
3  NaN  NaN  NaN  
4  NaN  NaN    3

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[0. 0. 0.]
[[-0. -0. -0.]
 [-0. -0. -0.]
 [-0. -0. -0.]]
[[0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 0.]]
[[-0. -0. -0.]
 [-0. -0. -0.]
 [-0. -0. -0.]]


nan

In [112]:
compute_alpha("Specialists data", "Covid_Probabilityv1-2020-10-04T1837-DataHunt.csv", "T1.Q6", "nominal", 6)

There are 0 rows where all values are missing
There are 0 cols where all values are missing
[array(['T1.Q6.A1', nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, array([], dtype=object), nan, nan, nan,
       nan, nan, nan, nan, 'T1.Q6.A1', nan, nan, nan, nan, nan, nan,
       'T1.Q6.A1', nan, nan, nan, nan, nan, nan, 'T1.Q6.A1', nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, 'T1.Q6.A1', nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       'T1.Q6.A1', nan, nan, nan, nan, nan, nan, nan, nan, nan,
       'T1.Q6.A3', nan, nan, nan, nan, nan, nan, nan, na

C:\Users\thefi\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  # Remove the CWD from sys.path while we load stuff.


nan

In [139]:
a = [[np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, 4, 1, 2, np.nan, np.nan, np.nan],
     [1, 2, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, 3],
     [np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan],
     [3, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan]]

In [145]:
print(round(alpha(reliability_data=a, level_of_measurement='nominal'), 10))

[[0. 0. 1. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]]
[1. 0. 1. 0.]
[[0. 0. 1. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 1. 1. 1.]
 [1. 0. 1. 1.]
 [1. 1. 0. 1.]
 [1. 1. 1. 0.]]
[[0. 0. 1. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 0.]]
0.0


# Triager Tasks

## Example of Triager_split()

In [46]:
triager_split("Triager data", "Triager output")

Triager Tranformation Done! Ready to be imported to uAlpha!


## Example of resolving overlap

In [41]:
a = pd.read_csv("example.csv")
a.drop(a.columns[0], axis=1, inplace=True)
a

contributor_uuid  topic_name  start_pos  blank  end_pos  \
0           aac18e           2        136    NaN      287   
1           aac18e           2        563    NaN      776   
2           aac18e           2        651    NaN      667   

   article_text_length  article_number                     created  \
0                 1870          100054  2020-03-18 00:15:42.364545   
1                 1870          100054  2020-03-18 00:15:42.364545   
2                 1870          100054  2020-03-18 00:15:42.364545   

   cumulative  start_pos_adjusted  end_pos_adjusted  
0        5755                4021              4172  
1        5755                4448              4661  
2        5755                4536              4552

In [42]:
a = resolve_overlapping(a)
a

contributor_uuid  topic_name  start_pos  blank  end_pos  \
0           aac18e           2        136    NaN      287   
1           aac18e           2        563    NaN      776   

   article_text_length  article_number                     created  \
0                 1870          100054  2020-03-18 00:15:42.364545   
1                 1870          100054  2020-03-18 00:15:42.364545   

   cumulative  start_pos_adjusted  end_pos_adjusted  
0        5755                4021              4172  
1        5755                4448              4661

In [45]:
detect_overlapping("Triager output", "Covid-Triager-Arguments.csv")

## Example of removing a row

In [43]:
a = pd.DataFrame(index=np.array([23, 24, 25, 26, 27]), data={"first": [1, 2, 3, 4, 5]})
a

first
23      1
24      2
25      3
26      4
27      5

In [44]:
a.drop(25, inplace=True)
a

first
23      1
24      2
26      4
27      5