In [1]:
# import necessary modules 
# please run this everytime you open it
import pandas as pd 
import numpy as np 
import matplotlib as plt 
import seaborn as sns
import re
import os

In [2]:
# import krippendorff.py
%run krippendorff.py
%run Validation.ipynb

In [3]:
to_reliability("Specialists data", "Covid_Evidencev1-2020-10-04T1836-DataHunt.csv", "cl", "T1.Q11")

array([[ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ...,  0.,  1.,  0.]])

In [4]:
compute_alpha("Specialists data",
              "Covid_Evidencev1-2020-10-04T1836-DataHunt.csv", "cl",
              "T1.Q11",
              "ordinal", 6)

0.072473

In [5]:
decompose_question("T1.Q11")

11

In [6]:
get_question_type("Argument relevance", "T1.Q3")

'mc'

**get_measurement**

In [7]:
for file in os.listdir("Specialists data"):
    name = os.path.join("Specialists data", file)
    df = pd.read_csv(name)
    topic = get_topic(df)
    print(file)
    for question in df["question_label"].unique():
        cur = get_question_type(topic, question)
        if cur == 'mc':
            measurement = get_measurement(topic, question)
        else:
            measurement = ''
        print(question, cur, measurement)

Covid_ArgumentRelevancev1.2-2020-10-04T1802-DataHunt.csv
T1.Q1 mc categorical
Covid_Evidencev1-2020-10-04T1836-DataHunt.csv
T1.Q1 cl 
T1.Q2 cl 
T1.Q3 tx 
T1.Q7 tx 
T1.Q8 mc ordinal
T1.Q9 mc categorical
T1.Q12 mc ordinal
T1.Q13 mc ordinal
T1.Q14 mc ordinal
T1.Q4 mc ordinal
T1.Q10 mc ordinal
T1.Q11 mc ordinal
T1.Q5 mc ordinal
T1.Q6 mc categorical
Covid_Holisiticv1.2-2020-10-04T1803-DataHunt.csv
T1.Q1 mc categorical
T1.Q3 cl 
T1.Q5 mc categorical
T1.Q6 cl 
T1.Q7 mc ordinal
T1.Q8 mc ordinal
T1.Q9 cl 
T1.Q10 cl 
T1.Q11 mc ordinal
T1.Q12 mc ordinal
T1.Q13 mc ordinal
T1.Q14 mc categorical
T1.Q15 cl 
T1.Q17 mc ordinal
T1.Q18 mc ordinal
T1.Q16 tx 
Covid_Languagev1.1-2020-10-04T1837-DataHunt.csv
T1.Q12 mc ordinal
T1.Q14 mc ordinal
T1.Q15 mc ordinal
T1.Q1 cl 
T1.Q11 mc ordinal
T1.Q3 mc ordinal
T1.Q13 mc ordinal
T1.Q5 mc ordinal
T1.Q6 cl 
T1.Q7 tx 
T1.Q2 mc ordinal
T1.Q9 mc ordinal
T1.Q10 mc ordinal
Covid_Probabilityv1-2020-10-04T1837-DataHunt.csv
T1.Q1 mc ordinal
T1.Q5 mc ordinal
T1.Q6 mc categor

In [33]:
for file in os.listdir("Specialists data"):
    print()
    print(file)
    name = os.path.join("Specialists data", file)
    df = pd.read_csv(name)
    topic = get_topic(df)
    for question in df["question_label"].unique():
        # "mc"/"cl"/"tx"
        question_type = get_question_type(topic, question)
        if question_type == "mc":
            # "categorical"/"ordinal"
            try:
                reliability_array = to_reliability("Specialists data", 
                                                   file,
                                                   "mc", question)
            except:
                reliability_array = to_reliability("Specialists data", 
                                                   file,
                                                   "cl", question)
            measurement = get_measurement(topic, question)
            try:
                value = alpha(reliability_data=reliability_array, level_of_measurement=measurement)
                print(question, question_type, value)
            except Exception as e: 
                print(question, question_type, e)
        elif question_type == "cl":
            reliability_array = to_reliability("Specialists data", 
                                                file,
                                                "cl", question)
            try:
                value = alpha(reliability_data=reliability_array, level_of_measurement="nominal")
                print(question, question_type, value)
            except Exception as e: 
                print(question, question_type, e)


Covid_ArgumentRelevancev1.2-2020-10-04T1802-DataHunt.csv
T1.Q1 mc 0.26865552903739065

Covid_Evidencev1-2020-10-04T1836-DataHunt.csv
T1.Q1 cl 0.302802702031877


C:\Users\thefi\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if __name__ == '__main__':


T1.Q2 cl 0.13010568324524285
T1.Q8 mc 0.14191752542031244
T1.Q9 mc 0.2917096633618791
T1.Q12 mc 0.2129080208377916
T1.Q13 mc 0.08733542608940825
T1.Q14 mc 0.058689609257064235
T1.Q4 mc 0.13539407234342216
T1.Q10 mc 0.13299611068894113
T1.Q11 mc 0.01751555367203661
T1.Q5 mc 0.16681664159688137
T1.Q6 mc 0.0

Covid_Holisiticv1.2-2020-10-04T1803-DataHunt.csv
T1.Q1 mc There has to be more than one value in the domain.
T1.Q3 cl nan
T1.Q5 mc nan
T1.Q6 cl nan
T1.Q7 mc nan
T1.Q8 mc nan
T1.Q9 cl There has to be more than one value in the domain.
T1.Q10 cl nan
T1.Q11 mc nan
T1.Q12 mc nan
T1.Q13 mc nan
T1.Q14 mc nan
T1.Q15 cl nan
T1.Q17 mc nan
T1.Q18 mc nan

Covid_Languagev1.1-2020-10-04T1837-DataHunt.csv
T1.Q12 mc 0.661538232064774
T1.Q14 mc 0.08973522455475325
T1.Q15 mc 0.056751754679111865
T1.Q1 cl 0.23861117427130862
T1.Q11 mc 0.016253777872968223
T1.Q3 mc 0.1423539695512578
T1.Q13 mc 0.0
T1.Q5 mc 0.07647574297067383
T1.Q6 cl 0.20662067215953595
T1.Q2 mc 0.4292040531021921
T1.Q9 mc 0.721919924

In [3]:
source = pd.read_csv("Specialists data/Covid_Holisiticv1.2-2020-10-04T1803-DataHunt.csv")
source = source[source["question_label"] == "T1.Q1"]
cols = ["quiz_task_uuid", "contributor_uuid", "question_label", "answer_label"]
source = source.reindex(columns=cols)
source = pd.pivot_table(data=source, values="answer_label", index="contributor_uuid",
                        columns="quiz_task_uuid", aggfunc=select)
array = source.to_numpy()
array = to_int(array)
display(array)
try:
    print(np.round(alpha(reliability_data=array, level_of_measurement="nominal"), 5))
except Exception as e: 
    print(e)

array([[1, nan, nan, nan],
       [nan, 1, 1, 1]], dtype=object)

There has to be more than one value in the domain.


In [28]:
source = pd.read_csv("Specialists data/Covid_Holisiticv1.2-2020-10-04T1803-DataHunt.csv")
source = source[source["question_label"] == "T1.Q5"]
cols = ["quiz_task_uuid", "contributor_uuid", "question_label", "answer_label"]
source = source.reindex(columns=cols)
source = pd.pivot_table(data=source, values="answer_label", index="contributor_uuid",
                        columns="quiz_task_uuid", aggfunc=select)
array = source.to_numpy()
array = to_int(array)
display(array)
try:
    print(np.round(alpha(reliability_data=array, level_of_measurement="nominal"), 5))
except Exception as e: 
    print(e)

array([[2, nan, nan, nan],
       [nan, 4, 2, 5]], dtype=object)

nan


In [29]:
source = pd.read_csv("Specialists data/Covid_Holisiticv1.2-2020-10-04T1803-DataHunt.csv")
source = source[source["question_label"] == "T1.Q7"]
cols = ["quiz_task_uuid", "contributor_uuid", "question_label", "answer_label"]
source = source.reindex(columns=cols)
source = pd.pivot_table(data=source, values="answer_label", index="contributor_uuid",
                        columns="quiz_task_uuid", aggfunc=select)
array = source.to_numpy()
array = to_int(array)
display(array)
try:
    print(np.round(alpha(reliability_data=array, level_of_measurement="nominal"), 5))
except Exception as e: 
    print(e)

array([[2, nan, nan, nan],
       [nan, 4, 2, 5]], dtype=object)

nan


In [30]:
source = pd.read_csv("Specialists data/Covid_Holisiticv1.2-2020-10-04T1803-DataHunt.csv")
source = source[source["question_label"] == "T1.Q8"]
cols = ["quiz_task_uuid", "contributor_uuid", "question_label", "answer_label"]
source = source.reindex(columns=cols)
source = pd.pivot_table(data=source, values="answer_label", index="contributor_uuid",
                        columns="quiz_task_uuid", aggfunc=select)
array = source.to_numpy()
array = to_int(array)
display(array)
try:
    print(np.round(alpha(reliability_data=array, level_of_measurement="nominal"), 5))
except Exception as e: 
    print(e)

array([[5, nan, nan, nan],
       [nan, 1, 4, 1]], dtype=object)

nan
