In [1]:
# import necessary modules 
# please run this everytime you open it
import pandas as pd 
import numpy as np 
import matplotlib as plt 
import seaborn as sns
import re
import os

In [14]:
# import krippendorff.py
%run krippendorff.py
%run Validation.ipynb

In [3]:
to_reliability("Specialists data", "Covid_Evidencev1-2020-10-04T1836-DataHunt.csv", "cl", "T1.Q11")

array([[ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ...,  0.,  1.,  0.]])

In [4]:
compute_alpha("Specialists data",
              "Covid_Evidencev1-2020-10-04T1836-DataHunt.csv", "cl",
              "T1.Q11",
              "ordinal", 6)

0.072473

In [5]:
decompose_question("T1.Q11")

11

In [6]:
get_question_type("Argument relevance", "T1.Q3")

'mc'

**get_measurement**

In [17]:
get_question_types("Specialists DataHuntByCase")

Covid_ArgumentRelevancev1.2-2020-11-15T0217-DataHuntByCase.csv
T1.Q1 mc nominal
Covid_Evidencev1-2020-11-15T0322-DataHuntByCase.csv
T1.Q1 cl 
T1.Q2 cl 
T1.Q3 tx 
T1.Q7 tx 
T1.Q8 mc ordinal
T1.Q9 mc nominal
T1.Q12 mc ordinal
T1.Q13 mc ordinal
T1.Q14 mc ordinal
T1.Q4 mc ordinal
T1.Q10 mc ordinal
T1.Q11 mc ordinal
T1.Q5 mc ordinal
T1.Q6 mc nominal
Covid_Holisiticv1.2-2020-11-15T0325-DataHuntByCase.csv
T1.Q1 mc nominal
T1.Q3 cl 
T1.Q5 mc nominal
T1.Q6 cl 
T1.Q7 mc ordinal
T1.Q8 mc ordinal
T1.Q9 cl 
T1.Q10 cl 
T1.Q11 mc ordinal
T1.Q12 mc ordinal
T1.Q13 mc ordinal
T1.Q14 mc nominal
T1.Q15 cl 
T1.Q17 mc ordinal
T1.Q18 mc ordinal
T1.Q4 tx 
T1.Q2 tx 
T1.Q16 tx 
Covid_Languagev1.1-2020-11-15T0327-DataHuntByCase.csv
T1.Q12 mc ordinal
T1.Q14 mc ordinal
T1.Q15 mc ordinal
T1.Q1 cl 
T1.Q11 mc ordinal
T1.Q3 mc ordinal
T1.Q13 mc ordinal
T1.Q5 mc ordinal
T1.Q6 cl 
T1.Q7 tx 
T1.Q2 mc ordinal
T1.Q9 mc ordinal
T1.Q10 mc ordinal
Covid_Probabilityv1-2020-11-15T0328-DataHuntByCase.csv
T1.Q1 mc ordinal
T1.Q5 m

In [18]:
calculate_alpha("Specialists DataHuntByCase")


Covid_ArgumentRelevancev1.2-2020-11-15T0217-DataHuntByCase.csv
T1.Q1 mc nominal 0.1875967900886949

Covid_Evidencev1-2020-11-15T0322-DataHuntByCase.csv
T1.Q1 cl 0.3157522469395442
T1.Q2 cl 0.16664606219229228
T1.Q8 mc ordinal 0.13905618090209415
T1.Q9 mc nominal 0.05326450481175238
T1.Q12 mc ordinal 0.15015094028171772
T1.Q13 mc ordinal 0.033136711920013884
T1.Q14 mc ordinal -0.0016592887729971473
T1.Q4 mc ordinal 0.13992877091981604
T1.Q10 mc ordinal 0.12271907006150373
T1.Q11 mc ordinal 0.027971037149836064
T1.Q5 mc ordinal 0.42758458348799944
T1.Q6 mc nominal 0.0

Covid_Holisiticv1.2-2020-11-15T0325-DataHuntByCase.csv
T1.Q1 mc nominal -0.008620689655172376
T1.Q3 cl 0.41069330199764986
T1.Q5 mc nominal 0.23026315789473673
T1.Q6 cl 0.042472666105971446
T1.Q7 mc ordinal 0.5911764705882353
T1.Q8 mc ordinal 0.44200000000000006
T1.Q9 cl 0.4693877551020408
T1.Q10 cl 0.14930555555555558
T1.Q11 mc ordinal 0.26049999999999995
T1.Q12 mc ordinal 0.6415
T1.Q13 mc ordinal 0.0
T1.Q14 mc nominal 0

**Why nan?**

In [43]:
source = pd.read_csv("Specialists DataHuntByCase/Covid_Holisiticv1.2-2020-10-04T1803-DataHuntByCase.csv")
source = source[source["question_label"] == "T1.Q5"]
cols = ["quiz_task_uuid", "contributor_uuid", "question_label", "answer_label"]
source = source.reindex(columns=cols)
source = pd.pivot_table(data=source, values="answer_label", index="contributor_uuid",
                        columns="quiz_task_uuid", aggfunc=select)
array = source.to_numpy()
array = to_int(array)
display(array)
try:
    print(np.round(alpha(reliability_data=array, level_of_measurement="nominal"), 5))
except Exception as e: 
    print(e)

array([[2, nan, nan, nan],
       [nan, 4, 2, 5]], dtype=object)

nan


In [19]:
source = pd.read_csv("Specialists DataHuntByCase/Covid_Reasoningv1-2020-11-15T0331-DataHuntByCase.csv")
source = source[source["question_label"] == "T1.Q5"]
cols = ["quiz_task_uuid", "contributor_uuid", "question_label", "answer_label"]
source = source.reindex(columns=cols)
source = pd.pivot_table(data=source, values="answer_label", index="contributor_uuid",
                        columns="quiz_task_uuid", aggfunc=select)
array = source.to_numpy()
array = to_int(array)
display(array)
try:
    print(np.round(alpha(reliability_data=array, level_of_measurement="nominal"), 5))
except Exception as e: 
    print(e)

array([[nan, 3],
       [3, nan]], dtype=object)

There has to be more than one value in the domain.


In [20]:
source = pd.read_csv("Specialists DataHuntByCase/Covid_Reasoningv1-2020-11-15T0331-DataHuntByCase.csv")
source = source[source["question_label"] == "T1.Q4"]
cols = ["quiz_task_uuid", "contributor_uuid", "question_label", "answer_label"]
source = source.reindex(columns=cols)
source = pd.pivot_table(data=source, values="answer_label", index="contributor_uuid",
                        columns="quiz_task_uuid", aggfunc=select)
array = source.to_numpy()
array = to_int(array)
display(array)
try:
    print(np.round(alpha(reliability_data=array, level_of_measurement="nominal"), 5))
except Exception as e: 
    print(e)

array([[nan, 3],
       [1, nan]], dtype=object)

nan


**More than one value in the domain?**

In [3]:
source = pd.read_csv("Specialists data/Covid_Holisiticv1.2-2020-10-04T1803-DataHunt.csv")
source = source[source["question_label"] == "T1.Q1"]
cols = ["quiz_task_uuid", "contributor_uuid", "question_label", "answer_label"]
source = source.reindex(columns=cols)
source = pd.pivot_table(data=source, values="answer_label", index="contributor_uuid",
                        columns="quiz_task_uuid", aggfunc=select)
array = source.to_numpy()
array = to_int(array)
display(array)
try:
    print(np.round(alpha(reliability_data=array, level_of_measurement="nominal"), 5))
except Exception as e: 
    print(e)

array([[1, nan, nan, nan],
       [nan, 1, 1, 1]], dtype=object)

There has to be more than one value in the domain.


**Why negative?**

In [41]:
source = pd.read_csv("Specialists DataHuntByCase/Covid_Evidencev1-2020-10-04T1836-DataHuntByCase.csv")
source = source[source["question_label"] == "T1.Q14"]
cols = ["quiz_task_uuid", "contributor_uuid", "question_label", "answer_label"]
source = source.reindex(columns=cols)
source = pd.pivot_table(data=source, values="answer_label", index="contributor_uuid",
                        columns="quiz_task_uuid", aggfunc=select)
array = source.to_numpy()
array = to_int(array)
try:
    print(np.round(alpha(reliability_data=array, level_of_measurement="nominal"), 5))
except Exception as e: 
    print(e)
# df = pd.DataFrame(array)
# df.to_excel('example2.xlsx')

-0.00846


https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4974794/#:~:text=Krippendorff's%20alpha%20in%20contrast%20is,negative%20values%20indicate%20inverse%20agreement.<br>
Krippendorff’s alpha in contrast is based on the observed disagreement corrected for disagreement expected by chance. This leads to a range of −1 to 1 for both measures, where 1 indicates perfect agreement, 0 indicates no agreement beyond chance and negative values indicate inverse agreement.