In [25]:
# import necessary modules 
# please run this everytime you open it
import pandas as pd 
import numpy as np 
import matplotlib as plt 
import seaborn as sns
import re
import os

In [133]:
# import krippendorff.py
%run krippendorff.py
%run Validation.ipynb

In [3]:
to_reliability("Specialists data", "Covid_Evidencev1-2020-10-04T1836-DataHunt.csv", "cl", "T1.Q11")

array([[ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ...,  0.,  1.,  0.]])

In [4]:
compute_alpha("Specialists data",
              "Covid_Evidencev1-2020-10-04T1836-DataHunt.csv", "cl",
              "T1.Q11",
              "ordinal", 6)

0.072473

In [5]:
decompose_question("T1.Q11")

11

In [6]:
get_question_type("Argument relevance", "T1.Q3")

'mc'

**get_measurement**

In [17]:
get_question_types("Specialists DataHuntByCase")

Covid_ArgumentRelevancev1.2-2020-11-15T0217-DataHuntByCase.csv
T1.Q1 mc nominal
Covid_Evidencev1-2020-11-15T0322-DataHuntByCase.csv
T1.Q1 cl 
T1.Q2 cl 
T1.Q3 tx 
T1.Q7 tx 
T1.Q8 mc ordinal
T1.Q9 mc nominal
T1.Q12 mc ordinal
T1.Q13 mc ordinal
T1.Q14 mc ordinal
T1.Q4 mc ordinal
T1.Q10 mc ordinal
T1.Q11 mc ordinal
T1.Q5 mc ordinal
T1.Q6 mc nominal
Covid_Holisiticv1.2-2020-11-15T0325-DataHuntByCase.csv
T1.Q1 mc nominal
T1.Q3 cl 
T1.Q5 mc nominal
T1.Q6 cl 
T1.Q7 mc ordinal
T1.Q8 mc ordinal
T1.Q9 cl 
T1.Q10 cl 
T1.Q11 mc ordinal
T1.Q12 mc ordinal
T1.Q13 mc ordinal
T1.Q14 mc nominal
T1.Q15 cl 
T1.Q17 mc ordinal
T1.Q18 mc ordinal
T1.Q4 tx 
T1.Q2 tx 
T1.Q16 tx 
Covid_Languagev1.1-2020-11-15T0327-DataHuntByCase.csv
T1.Q12 mc ordinal
T1.Q14 mc ordinal
T1.Q15 mc ordinal
T1.Q1 cl 
T1.Q11 mc ordinal
T1.Q3 mc ordinal
T1.Q13 mc ordinal
T1.Q5 mc ordinal
T1.Q6 cl 
T1.Q7 tx 
T1.Q2 mc ordinal
T1.Q9 mc ordinal
T1.Q10 mc ordinal
Covid_Probabilityv1-2020-11-15T0328-DataHuntByCase.csv
T1.Q1 mc ordinal
T1.Q5 m

In [134]:
calculate_alpha("Specialists DataHuntByCase", "Specialists output")


Covid_ArgumentRelevancev1.2-2020-11-15T0217-DataHuntByCase.csv
T1.Q1 mc nominal alpha: 0.1875967900886949 # of pairable values: 141

Covid_Evidencev1-2020-11-15T0322-DataHuntByCase.csv
T1.Q1 cl T1.Q1.A1 alpha: 0.21019130178515877 # of pairable values: 379
T1.Q1 cl T1.Q1.A2 alpha: 0.008926765298146289 # of pairable values: 379
T1.Q1 cl T1.Q1.A3 alpha: 0.16752661089110943 # of pairable values: 379
T1.Q2 cl T1.Q2.A8 alpha: 0.0005221386800333683 # of pairable values: 137
T1.Q2 cl T1.Q2.A3 alpha: 0.07905511811023624 # of pairable values: 137
T1.Q2 cl T1.Q2.A9 alpha: 0.08756912943515816 # of pairable values: 137
T1.Q2 cl T1.Q2.A6 alpha: 0.03340440653873489 # of pairable values: 137
T1.Q2 cl T1.Q2.A1 alpha: 0.06689722736983739 # of pairable values: 137
T1.Q2 cl T1.Q2.A2 alpha: -0.025345181134655004 # of pairable values: 137
T1.Q2 cl T1.Q2.A4 alpha: 0.040877628313961134 # of pairable values: 137
T1.Q2 cl T1.Q2.A7 alpha: 0.06798245614035092 # of pairable values: 137
T1.Q2 cl T1.Q2.A5 alpha: 0.

C:\Users\thefi\Desktop\PE-Validation-Fall-20\krippendorff.py:278: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - (o * d).sum() / (e * d).sum()


T1.Q14 mc ordinal alpha: -0.011517488028051304 # of pairable values: 351
T1.Q15 mc ordinal alpha: -0.034429055350072346 # of pairable values: 351
T1.Q1 cl T1.Q1.A13 alpha: 0.2629527308252234 # of pairable values: 349
T1.Q1 cl T1.Q1.A11 alpha: -0.0019197929069740827 # of pairable values: 349
T1.Q1 cl T1.Q1.A9 alpha: 0.13761822660546952 # of pairable values: 349
T1.Q1 cl T1.Q1.A3 alpha: 0.05279263509352017 # of pairable values: 349
T1.Q1 cl T1.Q1.A12 alpha: 0.041152679474216414 # of pairable values: 349
T1.Q1 cl T1.Q1.A2 alpha: 0.24911047305028144 # of pairable values: 349
T1.Q1 cl T1.Q1.A7 alpha: 0.11317600786627324 # of pairable values: 349
T1.Q1 cl T1.Q1.A10 alpha: -0.008695652173912993 # of pairable values: 349
T1.Q1 cl T1.Q1.A4 alpha: 0.12851078745815592 # of pairable values: 349
T1.Q1 cl T1.Q1.A8 alpha: 0.0820969337289813 # of pairable values: 349
T1.Q1 cl T1.Q1.A1 alpha: 0.26779501149971263 # of pairable values: 349
T1.Q1 cl T1.Q1.A6 alpha: 0.2940032183086 # of pairable values: 34

In [139]:
df = pd.read_csv("Specialists DataHuntByCase/Covid_Evidencev1-2020-11-15T0322-DataHuntByCase.csv")
df = df[df["question_label"] == "T1.Q1"]
cols = ["quiz_task_uuid", "contributor_uuid", "answer_label"]
df = df.reindex(columns=cols)
# how many answer_labels are there 
# answers - 'answer_label_T1.Q1.A1'
answers = ['answer_label_' + answer for answer in df["answer_label"].unique()]
# one-hot-encode
copy = pd.get_dummies(df, columns = ["answer_label"])
# iterate through columns 
for col in answers: 
    cur_col = ["quiz_task_uuid", "contributor_uuid"] + [col]
    df_slice = copy.reindex(columns=cur_col).copy()
    try:
        df_slice = pd.pivot_table(df_slice, values=col, index="contributor_uuid", 
                              columns='quiz_task_uuid', aggfunc=lambda x: list(x)[0])
        array = df_slice.to_numpy()
        display(array)
        pairs = count_pairable(array)
        display(pairs)
    except Exception as e:
        print(e)

array([[ 1.,  1.,  1., ...,  0.,  1.,  0.],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan,  0., ..., nan, nan,  0.]])

379

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan,  0., ..., nan, nan,  0.]])

379

array([[ 0.,  0.,  0., ...,  1.,  0.,  1.],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan,  1., ..., nan, nan,  1.]])

379

**develop cl**

In [39]:
df = pd.read_csv("Specialists DataHuntByCase/Covid_Evidencev1-2020-11-15T0322-DataHuntByCase.csv")
df = df[df["question_label"] == "T1.Q1"]
cols = ["quiz_task_uuid", "contributor_uuid", "question_label", "answer_label"]
df = df.reindex(columns=cols)
# how many answer_labels are there 
answers = 'answer_label_' + df["answer_label"].unique()
df = pd.get_dummies(df, columns = ["answer_label"])
display(df.head())
# iterate through the columns 
for col in answers: 
    cur_col = ["quiz_task_uuid", "contributor_uuid", "question_label"] + [col]
    df_slice = df.reindex(columns=cur_col).copy()
    display(df_slice.head())
    df_slice = pd.pivot_table(df_slice, values=col, index="contributor_uuid", 
                              columns='quiz_task_uuid', aggfunc=lambda x: x)
    display(df_slice.head())    
    array = df_slice.to_numpy()
    display(array)
    al = alpha(reliability_data=array, level_of_measurement="nominal")
    print(al)
    break

quiz_task_uuid  \
0   c5df7dbf-85ef-4935-81a7-c24daa809afe   
10  c5df7dbf-85ef-4935-81a7-c24daa809afe   
24  c5df7dbf-85ef-4935-81a7-c24daa809afe   
32  c5df7dbf-85ef-4935-81a7-c24daa809afe   
37  c5df7dbf-85ef-4935-81a7-c24daa809afe   

                        contributor_uuid question_label  \
0   e1ae8875-a398-4dde-8f4e-4b21109784e3          T1.Q1   
10  00f548b7-6b63-4b47-828e-8e416b6ca0e2          T1.Q1   
24  27815ad0-5b51-47b8-92b3-ff067d51bef2          T1.Q1   
32  079b1a81-8a5a-4b44-87c7-7cc2a2b13655          T1.Q1   
37  38afca81-b024-4930-991a-7d2ab2645109          T1.Q1   

    answer_label_T1.Q1.A1  answer_label_T1.Q1.A2  answer_label_T1.Q1.A3  
0                       1                      0                      0  
10                      0                      1                      0  
24                      1                      0                      0  
32                      0                      0                      1  
37                      0                      0                      1

quiz_task_uuid  \
0   c5df7dbf-85ef-4935-81a7-c24daa809afe   
10  c5df7dbf-85ef-4935-81a7-c24daa809afe   
24  c5df7dbf-85ef-4935-81a7-c24daa809afe   
32  c5df7dbf-85ef-4935-81a7-c24daa809afe   
37  c5df7dbf-85ef-4935-81a7-c24daa809afe   

                        contributor_uuid question_label  answer_label_T1.Q1.A1  
0   e1ae8875-a398-4dde-8f4e-4b21109784e3          T1.Q1                      1  
10  00f548b7-6b63-4b47-828e-8e416b6ca0e2          T1.Q1                      0  
24  27815ad0-5b51-47b8-92b3-ff067d51bef2          T1.Q1                      1  
32  079b1a81-8a5a-4b44-87c7-7cc2a2b13655          T1.Q1                      0  
37  38afca81-b024-4930-991a-7d2ab2645109          T1.Q1                      0

quiz_task_uuid                       24657063-8eb5-4cf4-83d1-f39945922c3f  \
contributor_uuid                                                            
00f548b7-6b63-4b47-828e-8e416b6ca0e2                                    1   
070268de-067c-463b-9ad3-5c88292d881e                                  NaN   
079b1a81-8a5a-4b44-87c7-7cc2a2b13655                                  NaN   
082a8363-a579-41b4-8918-c166fec3a3a4                                  NaN   
09df3ada-e5a8-4419-b78a-e0d1e9b37484                                  NaN   

quiz_task_uuid                       270ea60c-f961-402b-96d5-c015fac1960d  \
contributor_uuid                                                            
00f548b7-6b63-4b47-828e-8e416b6ca0e2                                    1   
070268de-067c-463b-9ad3-5c88292d881e                                  NaN   
079b1a81-8a5a-4b44-87c7-7cc2a2b13655                                  NaN   
082a8363-a579-41b4-8918-c166fec3a3a4                                  NaN   
09df3ada-e5a8-4419-b78a-e0d1e9b37484                                  NaN   

quiz_task_uuid                       441e43ab-6be0-4a3a-820d-72f07efee748  \
contributor_uuid                                                            
00f548b7-6b63-4b47-828e-8e416b6ca0e2                                    1   
070268de-067c-463b-9ad3-5c88292d881e                                  NaN   
079b1a81-8a5a-4b44-87c7-7cc2a2b13655                                  NaN   
082a8363-a579-41b4-8918-c166fec3a3a4                                    0   
09df3ada-e5a8-4419-b78a-e0d1e9b37484                                    0   

quiz_task_uuid                       5985e15b-66bd-41c5-9659-86fab8376b8d  \
contributor_uuid                                                            
00f548b7-6b63-4b47-828e-8e416b6ca0e2                                    1   
070268de-067c-463b-9ad3-5c88292d881e                                  NaN   
079b1a81-8a5a-4b44-87c7-7cc2a2b13655                                  NaN   
082a8363-a579-41b4-8918-c166fec3a3a4                                  NaN   
09df3ada-e5a8-4419-b78a-e0d1e9b37484                                  NaN   

quiz_task_uuid                       5ce23012-9188-4884-a734-eeaf8dc19639  \
contributor_uuid                                                            
00f548b7-6b63-4b47-828e-8e416b6ca0e2                                    1   
070268de-067c-463b-9ad3-5c88292d881e                                  NaN   
079b1a81-8a5a-4b44-87c7-7cc2a2b13655                                  NaN   
082a8363-a579-41b4-8918-c166fec3a3a4                                  NaN   
09df3ada-e5a8-4419-b78a-e0d1e9b37484                                  NaN   

quiz_task_uuid                       79826d5e-97f6-4cb3-aea0-e5fe66a344aa  \
contributor_uuid                                                            
00f548b7-6b63-4b47-828e-8e416b6ca0e2                                    1   
070268de-067c-463b-9ad3-5c88292d881e                                  NaN   
079b1a81-8a5a-4b44-87c7-7cc2a2b13655                                  NaN   
082a8363-a579-41b4-8918-c166fec3a3a4                                  NaN   
09df3ada-e5a8-4419-b78a-e0d1e9b37484                                  NaN   

quiz_task_uuid                       af2993a0-d043-4c3a-aeb1-a522aed4f8a2  \
contributor_uuid                                                            
00f548b7-6b63-4b47-828e-8e416b6ca0e2                                    0   
070268de-067c-463b-9ad3-5c88292d881e                                  NaN   
079b1a81-8a5a-4b44-87c7-7cc2a2b13655                                  NaN   
082a8363-a579-41b4-8918-c166fec3a3a4                                  NaN   
09df3ada-e5a8-4419-b78a-e0d1e9b37484                                  NaN   

quiz_task_uuid                       b70500ce-f185-42bf-bced-76b4f968def0  \
contributor_uuid                                                            
00f548b7-6b63-4b47-828e-8e416b6ca0e2                              

array([[1, 1, 1, ..., 0, 1, 0],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, 0, ..., nan, nan, 0]], dtype=object)

0.21075517566856727


In [16]:
answers

array(['question_label_T1.Q1.A1', 'question_label_T1.Q1.A2',
       'question_label_T1.Q1.A3'], dtype=object)

**number of pairable values**

In [95]:
a = np.array([[1, np.nan, 2], 
              [2, np.nan, 3], 
              [3, 1, np.nan]])

In [113]:
b = np.array([[1, np.nan], 
             [np.nan, 2]])

In [126]:
count_pairable(a)

5

In [127]:
count_pairable(b)

0

In [128]:
df = pd.read_csv("Specialists DataHuntByCase/Covid_Evidencev1-2020-11-15T0322-DataHuntByCase.csv")
df = df[df["question_label"] == 'T1.Q8']
cols = ["quiz_task_uuid", "contributor_uuid", "question_label", "answer_label"]
df = df.reindex(columns=cols)
df = pd.pivot_table(df, values='answer_label', index='contributor_uuid', columns='quiz_task_uuid', aggfunc=select)
# to numpy array
array = df.to_numpy()
# convert string to int 
array = to_int(array)
# return the array 
display(array)

array([[3, 4, 5, 4, 4, 4, 4, 2, 5, 4, 5, nan, 4, nan, 4, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, 2, nan, 5, nan, 3, nan,
        nan, nan],
       [nan, nan, 4, nan, nan, nan, nan, nan, 5, nan, nan, nan, nan, nan,
        nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, 3, nan, nan, nan, nan,
        nan, nan, nan],
       [nan, nan, 4, nan, nan, nan, nan, nan, 3, nan, nan, nan, nan, nan,
        nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, 4, nan, 3, nan,
        nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, 4, nan, 5, nan, 4, nan,
        nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, 5, nan, 3, nan,
        nan, nan],
       [nan, nan, 3, nan, nan, nan, nan, 4, nan, 4, nan, nan, nan, nan,
        nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, 1,
        nan, nan, nan],
       [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, 4,
        nan, nan, nan],
       

In [129]:
count_pairable(array)

139

**Function does not reduce**

In [64]:
df = pd.read_csv("Specialists DataHuntByCase/Covid_Languagev1.1-2020-11-15T0327-DataHuntByCase.csv")
df = df[df["question_label"] == 'T1.Q1']
cols = ["quiz_task_uuid", "contributor_uuid", "answer_label"]
df = df.reindex(columns=cols)
# how many answer_labels are there 
# answers - 'answer_label_T1.Q1.A1'
answers = ['answer_label_' + answer for answer in df["answer_label"].unique()]
if answers == []:
    print(question)
# one-hot-encode
df = pd.get_dummies(df, columns = ["answer_label"])
# issue - one contributor will have multiple rows
# combine 
# iterate through columns 
for col in answers: 
    cur_col = ["quiz_task_uuid", "contributor_uuid", "question_label"] + [col]
    df_slice = df.reindex(columns=cur_col).copy()
    try:
        df_slice = pd.pivot_table(df_slice, values=col, index="contributor_uuid", 
                                  columns='quiz_task_uuid', aggfunc=lambda x: list(x)[0])
        display(col)
        display(df_slice.head())
        array = df_slice.to_numpy()
        value = alpha(reliability_data=array, level_of_measurement="nominal")
        print(col, value)
        break
    except Exception as e:
        print(e)

'answer_label_T1.Q1.A13'

quiz_task_uuid                        00878ed9-a6f1-4e3c-8434-6e978ab9c50e  \
contributor_uuid                                                             
00f548b7-6b63-4b47-828e-8e416b6ca0e2                                   0.0   
0b2ee377-65f2-4ac1-98da-5bc093fee7aa                                   NaN   
0ba64400-eb62-4efc-b9b5-b601e7b40259                                   NaN   
0cdf31d0-1966-4f69-a0c8-c483788b5256                                   NaN   
0e4b8a3e-2714-4b5f-ba10-bb576aaa5cc6                                   NaN   

quiz_task_uuid                        06a60a10-cf7d-4d58-b57d-b99fa3e9cd40  \
contributor_uuid                                                             
00f548b7-6b63-4b47-828e-8e416b6ca0e2                                   NaN   
0b2ee377-65f2-4ac1-98da-5bc093fee7aa                                   NaN   
0ba64400-eb62-4efc-b9b5-b601e7b40259                                   NaN   
0cdf31d0-1966-4f69-a0c8-c483788b5256                                   0.0   
0e4b8a3e-2714-4b5f-ba10-bb576aaa5cc6                                   1.0   

quiz_task_uuid                        0b3af2cb-cd41-4a5f-908e-41456989356f  \
contributor_uuid                                                             
00f548b7-6b63-4b47-828e-8e416b6ca0e2                                   NaN   
0b2ee377-65f2-4ac1-98da-5bc093fee7aa                                   NaN   
0ba64400-eb62-4efc-b9b5-b601e7b40259                                   NaN   
0cdf31d0-1966-4f69-a0c8-c483788b5256                                   NaN   
0e4b8a3e-2714-4b5f-ba10-bb576aaa5cc6                                   NaN   

quiz_task_uuid                        0f08ea77-9be2-406f-a88c-d9e2917d716a  \
contributor_uuid                                                             
00f548b7-6b63-4b47-828e-8e416b6ca0e2                                   NaN   
0b2ee377-65f2-4ac1-98da-5bc093fee7aa                                   NaN   
0ba64400-eb62-4efc-b9b5-b601e7b40259                                   NaN   
0cdf31d0-1966-4f69-a0c8-c483788b5256                                   NaN   
0e4b8a3e-2714-4b5f-ba10-bb576aaa5cc6                                   NaN   

quiz_task_uuid                        3469147d-7ffb-4319-97f1-21b2e2fadfa5  \
contributor_uuid                                                             
00f548b7-6b63-4b47-828e-8e416b6ca0e2                                   0.0   
0b2ee377-65f2-4ac1-98da-5bc093fee7aa                                   NaN   
0ba64400-eb62-4efc-b9b5-b601e7b40259                                   NaN   
0cdf31d0-1966-4f69-a0c8-c483788b5256                                   NaN   
0e4b8a3e-2714-4b5f-ba10-bb576aaa5cc6                                   NaN   

quiz_task_uuid                        377e7638-d1b1-4f2c-ad56-f02be2bb2de5  \
contributor_uuid                                                             
00f548b7-6b63-4b47-828e-8e416b6ca0e2                                   NaN   
0b2ee377-65f2-4ac1-98da-5bc093fee7aa                                   NaN   
0ba64400-eb62-4efc-b9b5-b601e7b40259                                   NaN   
0cdf31d0-1966-4f69-a0c8-c483788b5256                                   0.0   
0e4b8a3e-2714-4b5f-ba10-bb576aaa5cc6                                   NaN   

quiz_task_uuid                        44032133-a9cd-4baa-a10d-2aab5cbf6372  \
contributor_uuid                                                             
00f548b7-6b63-4b47-828e-8e416b6ca0e2                                   NaN   
0b2ee377-65f2-4ac1-98da-5bc093fee7aa                                   NaN   
0ba64400-eb62-4efc-b9b5-b601e7b40259                                   NaN   
0cdf31d0-1966-4f69-a0c8-c483788b5256                                   0.0   
0e4b8a3e-2714-4b5f-ba10-bb576aaa5cc6                                   NaN   

quiz_task_uuid                        45fd13d3-90f5-45f9-9ddb-7e63ca2520c2  \
contributor_uuid                                                             
00f548b7-6b63-4

answer_label_T1.Q1.A13 0.2629527308252234


In [55]:
df = pd.read_csv("Specialists DataHuntByCase/Covid_Languagev1.1-2020-11-15T0327-DataHuntByCase.csv")
df = df[df["question_label"] == 'T1.Q1']
cols = ["quiz_task_uuid", "contributor_uuid", "answer_label"]
df = df.reindex(columns=cols)
# how many answer_labels are there 
# answers - 'answer_label_T1.Q1.A1'
answers = ['answer_label_' + answer for answer in df["answer_label"].unique()]
df = pd.get_dummies(df, columns = ["answer_label"])
df[(df["contributor_uuid"] == "1119f9ca-0dce-4a9e-b71e-5983833e8bbe") & 
   (df['quiz_task_uuid'] == "00878ed9-a6f1-4e3c-8434-6e978ab9c50e")]  

quiz_task_uuid  \
1733  00878ed9-a6f1-4e3c-8434-6e978ab9c50e   
1734  00878ed9-a6f1-4e3c-8434-6e978ab9c50e   
1735  00878ed9-a6f1-4e3c-8434-6e978ab9c50e   

                          contributor_uuid  answer_label_T1.Q1.A1  \
1733  1119f9ca-0dce-4a9e-b71e-5983833e8bbe                      0   
1734  1119f9ca-0dce-4a9e-b71e-5983833e8bbe                      0   
1735  1119f9ca-0dce-4a9e-b71e-5983833e8bbe                      0   

      answer_label_T1.Q1.A10  answer_label_T1.Q1.A11  answer_label_T1.Q1.A12  \
1733                       0                       0                       0   
1734                       0                       0                       0   
1735                       0                       0                       0   

      answer_label_T1.Q1.A13  answer_label_T1.Q1.A2  answer_label_T1.Q1.A3  \
1733                       0                      1                      0   
1734                       0                      0                      1   
1735                       0                      0                      1   

      answer_label_T1.Q1.A4  answer_label_T1.Q1.A5  answer_label_T1.Q1.A6  \
1733                      0                      0                      0   
1734                      0                      0                      0   
1735                      0                      0                      0   

      answer_label_T1.Q1.A7  answer_label_T1.Q1.A8  answer_label_T1.Q1.A9  
1733                      0                      0                      0  
1734                      0                      0                      0  
1735                      0                      0                      0

In [53]:
df = pd.read_csv("Specialists DataHuntByCase/Covid_Languagev1.1-2020-11-15T0327-DataHuntByCase.csv")
df = df[df["question_label"] == 'T1.Q1']
# cols = ["quiz_task_uuid", "contributor_uuid", "answer_label"]
# df = df.reindex(columns=cols)
df[(df["contributor_uuid"] == "1119f9ca-0dce-4a9e-b71e-5983833e8bbe") & 
   (df['quiz_task_uuid'] == "00878ed9-a6f1-4e3c-8434-6e978ab9c50e")]  

namespace                                      schema_sha256  \
1733  Covid_Languagev1.1  a6eca3a8c143a31e7b37337f744912e6d33c5b2f49cd29...   
1734  Covid_Languagev1.1  a6eca3a8c143a31e7b37337f744912e6d33c5b2f49cd29...   
1735  Covid_Languagev1.1  a6eca3a8c143a31e7b37337f744912e6d33c5b2f49cd29...   

                            quiz_task_uuid  \
1733  00878ed9-a6f1-4e3c-8434-6e978ab9c50e   
1734  00878ed9-a6f1-4e3c-8434-6e978ab9c50e   
1735  00878ed9-a6f1-4e3c-8434-6e978ab9c50e   

                                               task_url  \
1733  https://pe.goodlylabs.org/project/Covid_Langua...   
1734  https://pe.goodlylabs.org/project/Covid_Langua...   
1735  https://pe.goodlylabs.org/project/Covid_Langua...   

                                  tua_uuid  \
1733  7e23c306-d836-44a4-a2bc-c9f29e6bd82b   
1734  7e23c306-d836-44a4-a2bc-c9f29e6bd82b   
1735  7e23c306-d836-44a4-a2bc-c9f29e6bd82b   

                                     article_batch_name  article_number  \
1733  CovidArticles/ae2adbce9e3e65754de741c1aa4f734a...          100067   
1734  CovidArticles/ae2adbce9e3e65754de741c1aa4f734a...          100067   
1735  CovidArticles/ae2adbce9e3e65754de741c1aa4f734a...          100067   

                                       article_filename  \
1733  nancy-pelosi-owes-america-an-apology-for-coron...   
1734  nancy-pelosi-owes-america-an-apology-for-coron...   
1735  nancy-pelosi-owes-america-an-apology-for-coron...   

                                         article_sha256  article_text_length  \
1733  ae2adbce9e3e65754de741c1aa4f734a9a98c8006c25a7...                 2024   
1734  ae2adbce9e3e65754de741c1aa4f734a9a98c8006c25a7...                 2024   
1735  ae2adbce9e3e65754de741c1aa4f734a9a98c8006c25a7...                 2024   

      ... question_label                                      question_text  \
1733  ...          T1.Q1  Which of the following appears in the bolded t...   
1734  ...          T1.Q1  Which of the following appears in the bolded t...   
1735  ...          T1.Q1  Which of the following appears in the bolded t...   

      answer_label answer_content                           answer_uuid  \
1733      T1.Q1.A2   Exaggeration  8a1d3be8-2887-4f4c-8347-493c0f2493c2   
1734      T1.Q1.A3        Scandal  3c5ce6a2-1f72-405e-978d-287eb244ca69   
1735      T1.Q1.A3        Scandal  3c5ce6a2-1f72-405e-978d-287eb244ca69   

                        submitted_tua_uuid   answer_text  case_number  \
1733  244416c3-efaa-4ad5-b698-9cf9fa8cf154  Exaggeration            1   
1734  22c2db86-74d3-4bf5-8673-ce903e067852       Scandal            1   
1735  bd29122d-2e9e-45ee-94cf-f95f8b21ad8f       Scandal            2   

     highlight_count                                      submitted_tua  
1733               1  [{"case_number": 1, "text": "She was more inte...  
1734               1  [{"case_number": 1, "text": "politicize", "ans...  
1735               1  [{"case_number": 2, "text": "grab more money",...  

[3 rows x 29 columns]

In [47]:
df = pd.read_csv("Specialists DataHuntByCase/Covid_Languagev1.1-2020-11-15T0327-DataHuntByCase.csv")
df = df[df["question_label"] == 'T1.Q1']
cols = ["quiz_task_uuid", "contributor_uuid", "question_label", "answer_label"]
df = df.reindex(columns=cols)
# how many answer_labels are there 
# answers - 'answer_label_T1.Q1.A1'
answers = ['answer_label_' + answer for answer in df["answer_label"].unique()]
if answers == []:
    print(question)
# one-hot-encode
df = pd.get_dummies(df, columns = ["answer_label"])
df[(df["contributor_uuid"] == "00f548b7-6b63-4b47-828e-8e416b6ca0e2") & 
   (df['quiz_task_uuid'] == "00878ed9-a6f1-4e3c-8434-6e978ab9c50e")]  

quiz_task_uuid  \
1715  00878ed9-a6f1-4e3c-8434-6e978ab9c50e   
1716  00878ed9-a6f1-4e3c-8434-6e978ab9c50e   
1717  00878ed9-a6f1-4e3c-8434-6e978ab9c50e   
1718  00878ed9-a6f1-4e3c-8434-6e978ab9c50e   

                          contributor_uuid question_label  \
1715  00f548b7-6b63-4b47-828e-8e416b6ca0e2          T1.Q1   
1716  00f548b7-6b63-4b47-828e-8e416b6ca0e2          T1.Q1   
1717  00f548b7-6b63-4b47-828e-8e416b6ca0e2          T1.Q1   
1718  00f548b7-6b63-4b47-828e-8e416b6ca0e2          T1.Q1   

      answer_label_T1.Q1.A1  answer_label_T1.Q1.A10  answer_label_T1.Q1.A11  \
1715                      1                       0                       0   
1716                      0                       0                       0   
1717                      0                       0                       0   
1718                      0                       0                       0   

      answer_label_T1.Q1.A12  answer_label_T1.Q1.A13  answer_label_T1.Q1.A2  \
1715                       0                       0                      0   
1716                       0                       0                      0   
1717                       0                       0                      0   
1718                       0                       0                      0   

      answer_label_T1.Q1.A3  answer_label_T1.Q1.A4  answer_label_T1.Q1.A5  \
1715                      0                      0                      0   
1716                      0                      0                      0   
1717                      0                      1                      0   
1718                      1                      0                      0   

      answer_label_T1.Q1.A6  answer_label_T1.Q1.A7  answer_label_T1.Q1.A8  \
1715                      0                      0                      0   
1716                      1                      0                      0   
1717                      0                      0                      0   
1718                      0                      0                      0   

      answer_label_T1.Q1.A9  
1715                      0  
1716                      0  
1717                      0  
1718                      0

**Why nan?**

In [43]:
source = pd.read_csv("Specialists DataHuntByCase/Covid_Holisiticv1.2-2020-10-04T1803-DataHuntByCase.csv")
source = source[source["question_label"] == "T1.Q5"]
cols = ["quiz_task_uuid", "contributor_uuid", "question_label", "answer_label"]
source = source.reindex(columns=cols)
source = pd.pivot_table(data=source, values="answer_label", index="contributor_uuid",
                        columns="quiz_task_uuid", aggfunc=select)
array = source.to_numpy()
array = to_int(array)
display(array)
try:
    print(np.round(alpha(reliability_data=array, level_of_measurement="nominal"), 5))
except Exception as e: 
    print(e)

array([[2, nan, nan, nan],
       [nan, 4, 2, 5]], dtype=object)

nan


In [19]:
source = pd.read_csv("Specialists DataHuntByCase/Covid_Reasoningv1-2020-11-15T0331-DataHuntByCase.csv")
source = source[source["question_label"] == "T1.Q5"]
cols = ["quiz_task_uuid", "contributor_uuid", "question_label", "answer_label"]
source = source.reindex(columns=cols)
source = pd.pivot_table(data=source, values="answer_label", index="contributor_uuid",
                        columns="quiz_task_uuid", aggfunc=select)
array = source.to_numpy()
array = to_int(array)
display(array)
try:
    print(np.round(alpha(reliability_data=array, level_of_measurement="nominal"), 5))
except Exception as e: 
    print(e)

array([[nan, 3],
       [3, nan]], dtype=object)

There has to be more than one value in the domain.


In [20]:
source = pd.read_csv("Specialists DataHuntByCase/Covid_Reasoningv1-2020-11-15T0331-DataHuntByCase.csv")
source = source[source["question_label"] == "T1.Q4"]
cols = ["quiz_task_uuid", "contributor_uuid", "question_label", "answer_label"]
source = source.reindex(columns=cols)
source = pd.pivot_table(data=source, values="answer_label", index="contributor_uuid",
                        columns="quiz_task_uuid", aggfunc=select)
array = source.to_numpy()
array = to_int(array)
display(array)
try:
    print(np.round(alpha(reliability_data=array, level_of_measurement="nominal"), 5))
except Exception as e: 
    print(e)

array([[nan, 3],
       [1, nan]], dtype=object)

nan


**More than one value in the domain?**

In [3]:
source = pd.read_csv("Specialists data/Covid_Holisiticv1.2-2020-10-04T1803-DataHunt.csv")
source = source[source["question_label"] == "T1.Q1"]
cols = ["quiz_task_uuid", "contributor_uuid", "question_label", "answer_label"]
source = source.reindex(columns=cols)
source = pd.pivot_table(data=source, values="answer_label", index="contributor_uuid",
                        columns="quiz_task_uuid", aggfunc=select)
array = source.to_numpy()
array = to_int(array)
display(array)
try:
    print(np.round(alpha(reliability_data=array, level_of_measurement="nominal"), 5))
except Exception as e: 
    print(e)

array([[1, nan, nan, nan],
       [nan, 1, 1, 1]], dtype=object)

There has to be more than one value in the domain.


**Why negative?**

In [41]:
source = pd.read_csv("Specialists DataHuntByCase/Covid_Evidencev1-2020-10-04T1836-DataHuntByCase.csv")
source = source[source["question_label"] == "T1.Q14"]
cols = ["quiz_task_uuid", "contributor_uuid", "question_label", "answer_label"]
source = source.reindex(columns=cols)
source = pd.pivot_table(data=source, values="answer_label", index="contributor_uuid",
                        columns="quiz_task_uuid", aggfunc=select)
array = source.to_numpy()
array = to_int(array)
try:
    print(np.round(alpha(reliability_data=array, level_of_measurement="nominal"), 5))
except Exception as e: 
    print(e)
# df = pd.DataFrame(array)
# df.to_excel('example2.xlsx')

-0.00846


https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4974794/#:~:text=Krippendorff's%20alpha%20in%20contrast%20is,negative%20values%20indicate%20inverse%20agreement.<br>
Krippendorff’s alpha in contrast is based on the observed disagreement corrected for disagreement expected by chance. This leads to a range of −1 to 1 for both measures, where 1 indicates perfect agreement, 0 indicates no agreement beyond chance and negative values indicate inverse agreement.